---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hello-world-module.fullname" . }}
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hello-world-module.serviceAccountName" . }}
      securityContext:
        {{- include "fybrik.processPodSecurityContext" (dict "context" . "podSecurityContext" .Values.podSecurityContext) | nindent 8 }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "hello-world-module.fullname" . }}
        securityContext:
        {{toYaml .Values.containerSecurityContext | nindent 10 }}
        env:
        {{- range concat (.Values.global.environment) (.Values.environment | default list)}}
        - name: {{ .name | quote}}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.command }}
        command: {{ .Values.command }}
        {{- end }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: {{ template "hello-world-module.namewithsuffix" . }}-volume
          mountPath: "/hello-world-module"
          readOnly: true
      volumes:
      - name: {{ template "hello-world-module.namewithsuffix" . }}-volume
        configMap:
          name: {{ template "hello-world-module.namewithsuffix" . }}-config
          items:
          - key: conf.yaml
            path: conf.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
  backoffLimit: {{ .Values.backoffLimit }}
